###
GET http://localhost:8080/api/routes

###
@routeId = 22
GET http://localhost:8080/api/routes/{{routeId}}/directions

###
@direction = Southbound
GET http://localhost:8080/api/routes/{{routeId}}/directions/{{direction}}/stops

###
GET http://localhost:8080/api/routes/{{routeId}}/directions/{{direction}}/detours

###
@stopId = 18447
GET http://localhost:8080/api/routes/{{routeId}}/stops/{{stopId}}/arrivals

###
@busId = 4325
GET http://localhost:8080/api/buses/{{busId}}

###
GET http://localhost:8080/api/stations

###
@stationId = 41320
GET http://localhost:8080/api/stations/{{stationId}}/arrivals

###
@run = 409
GET http://localhost:8080/api/trains/{{run}}
