###
GET http://localhost:8080/api/buses/routes

###
@routeId = 22
GET http://localhost:8080/api/buses/routes/{{routeId}}/directions

###
@direction = Northbound
GET http://localhost:8080/api/buses/routes/{{routeId}}/directions/{{direction}}/stops

###
GET http://localhost:8080/api/trains/routes

###
GET http://localhost:8080/api/trains/stations

###
@stationId = 41320
GET http://localhost:8080/api/trains/stations/{{stationId}}/arrivals
